// examples/svelte/src/Item.svelte
<script>
    import { createEventDispatcher, tick } from 'svelte';

    export let item;

    const dispatch = createEventDispatcher();
    
    let editing = false;

    function removeItem() {
        dispatch('removeItem');
    }

    function startEdit() {
       editing = true;
    }

    function handleEdit(event) {
        if (event.key === "Enter")
            event.target.blur();
        else if (event.key === "Escape") 
            editing = false;
    }

    function updateItem(event) {
        if (!editing) return;
        const { value } = event.target;
        if (value.length) {
            item.title = value;
            dispatch('updateItem', item);
        } else {
          removeItem();
        }
        editing = false;
    }

    function toggleItem(item, event) {
        dispatch('toggleItem', item);
        item.completed = event.target.checked
    }

    async function focusInput(element) {
        await tick();
        element.focus();
    }
</script>

<li class:completed={item.completed} class:editing>
    <div class="view">
        <input class="toggle" type="checkbox" on:change={(event) => toggleItem(item,event)} checked={item.completed} />
        <!-- svelte-ignore a11y-label-has-associated-control -->
        <label on:dblclick={startEdit}>{item.title}</label>
        <button on:click={removeItem} class="destroy" />
    </div>

    {#if editing}
        <div class="input-container">
            <input value={item.title} id="edit-todo-input" class="edit" on:keydown={handleEdit} on:blur={updateItem} use:focusInput />
            <label class="visually-hidden" for="edit-todo-input">Edit Todo Input</label>
        </div>
    {/if}
</li>

// examples/react_ex/src/todo/components/item.jsx
import { memo, useState, useCallback } from "react";
import classnames from "classnames";

import { Input } from "./input";

export const Item = memo(function Item({
  todo,
  toggleItem,
  removeItem,
  updateItem,
  index,
}) {
  const [isWritable, setIsWritable] = useState(false);
  const { title, completed, id } = todo;

  const handleToggleItem = useCallback(() => {
    toggleItem(id);
  }, [id, toggleItem]);

  const handleRemoveItem = useCallback(() => {
    removeItem(id);
  }, [id, removeItem]);

  const handleUpdateItem = useCallback(
    (title) => {
      if (title.length === 0) {
        removeItem(id);
      } else {
        updateItem(id, title);
      }
      setIsWritable(false);
    },
    [id, removeItem, updateItem]
  );

  const handleDoubleClick = useCallback(() => {
    setIsWritable(true);
  }, []);

  const handleBlur = useCallback(() => {
    setIsWritable(false);
  }, []);

  return (
    <li
      className={classnames({ completed: todo.completed })}
      data-testid="todo-item"
    >
      <div className="view">
        {isWritable ? (
          <Input
            onSubmit={handleUpdateItem}
            label="Edit Todo Input"
            defaultValue={title}
            onBlur={handleBlur}
          />
        ) : (
          <>
            <input
              className="toggle"
              type="checkbox"
              data-testid="todo-item-toggle"
              checked={completed}
              onChange={handleToggleItem}
            />
            <label
              data-testid="todo-item-label"
              onDoubleClick={handleDoubleClick}
            >
              {title}
            </label>
            <button
              className="destroy"
              data-testid="todo-item-button"
              onClick={handleRemoveItem}
            />
          </>
        )}
      </div>
    </li>
  );
});
