// examples/react_ex/src/todo/components/footer.jsx
import { useCallback, useMemo } from "react";
import { useLocation } from "react-router-dom";
import classnames from "classnames";

export function Footer({ todos, removeCompletedItems }) {
  const { pathname: route } = useLocation();

  const activeTodos = useMemo(
    () => todos.filter((todo) => !todo.completed),
    [todos]
  );

  const handleRemoveCompletedItems = useCallback(
    () => removeCompletedItems(),
    [removeCompletedItems]
  );

  // prettier-ignore
  if (todos.length === 0)
        return null;

  return (
    <footer className="footer" data-testid="footer">
      <span className="todo-count">{`${activeTodos.length} ${
        activeTodos.length === 1 ? "item" : "items"
      } left!`}</span>
      <ul className="filters" data-testid="footer-navigation">
        <li>
          <a className={classnames({ selected: route === "/" })} href="#/">
            All
          </a>
        </li>
        <li>
          <a
            className={classnames({ selected: route === "/active" })}
            href="#/active"
          >
            Active
          </a>
        </li>
        <li>
          <a
            className={classnames({ selected: route === "/completed" })}
            href="#/completed"
          >
            Completed
          </a>
        </li>
      </ul>
      <button
        className="clear-completed"
        disabled={activeTodos.length === todos.length}
        onClick={handleRemoveCompletedItems}
      >
        Clear completed
      </button>
    </footer>
  );
}

// examples/angular/src/app/footer/footer.component.ts
import { Component, OnInit, inject } from '@angular/core';
import { Location } from '@angular/common';
import { Todo, TodosService } from '../todos.service';
import { ActivatedRoute, RouterLink } from '@angular/router';

@Component({
  selector: 'app-todo-footer',
  standalone: true,
  imports: [RouterLink],
  templateUrl: './footer.component.html',
})
export class FooterComponent implements OnInit {
  private location = inject(Location);
  private todosService = inject(TodosService);

  currentFilter: string = '';

  todos: Todo[] = [];
  activeTodos: Todo[] = [];
  completedTodos: Todo[] = [];

  constructor(private activatedRouter: ActivatedRoute) {}

  async ngOnInit(): Promise<void> {
    this.activatedRouter.queryParams.subscribe((params) => {
      this.currentFilter = params['filter'] || 'all';
    });

    this.todos = await this.todosService.getItems();
    this.activeTodos = await this.todosService.getItems('active');
    this.completedTodos = await this.todosService.getItems('completed');
  }

  get filter(): string {
    return this.location.path().split('/')[1] || 'all';
  }

  clearCompleted() {
    this.todosService.clearCompleted();
  }

  isActive(filter: string): boolean {
    return this.currentFilter === filter;
  }
}

@if (todos.length > 0) {
<footer class="footer">
  <span class="todo-count">
    <strong>{{ activeTodos.length }}</strong>
    {{ activeTodos.length === 1 ? "item" : "items" }} left
  </span>
  <ul class="filters">
    <li>
      <a routerLink="/" [class.selected]="isActive('all')">All</a>
    </li>
    <li>
      <a
        routerLink="/"
        [queryParams]="{ filter: 'active' }"
        [class.selected]="isActive('active')"
        >Active</a
      >
    </li>
    <li>
      <a
        routerLink="/"
        [queryParams]="{ filter: 'completed' }"
        [class.selected]="isActive('completed')"
        >Completed</a
      >
    </li>
  </ul>
  @if (completedTodos.length > 0) {
  <button type="button" class="clear-completed" (click)="clearCompleted()">
    Clear Completed
  </button>
  }
</footer>
}
